import { Course, Lesson, UserProfile, Worksheet } from './types';

export const MOCK_CURRENT_USER: UserProfile = {
  id: 'user-student-1',
  email: 'maya.student@deafacademy.edu',
  displayName: 'Maya Lin',
  role: 'student',
  gradeLevel: 'Grade 3',
  avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80',
  totalStars: 24,
  badgesUnlocked: ['Digital Navigator', 'Animal Sign Master', 'Story Explorer', 'Webcam Pro'],
};

export const MOCK_TEACHER: UserProfile = {
  id: 'user-teacher-1',
  email: 'jordan.ellis@deafacademy.edu',
  displayName: 'Mr. Jordan Ellis',
  role: 'teacher',
  gradeLevel: 'Elementary Specialist',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

export const MOCK_ADMIN: UserProfile = {
  id: 'user-admin-1',
  email: 'sarah.vance@deafacademy.edu',
  displayName: 'Director Sarah Vance',
  role: 'admin',
  gradeLevel: 'Administration',
  avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
};

export const MOCK_COURSES: Course[] = [
  {
    id: 'course-digital-literacy-1',
    title: 'Computer & Digital Literacy in Sign Language',
    description: 'Learn computer parts, web navigation icons, keyboarding, and video call etiquette tailored for Deaf students.',
    gradeLevel: 'Grade 2-5',
    category: 'Digital Literacy',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80',
    teacherId: 'user-teacher-1',
    teacherName: 'Mr. Jordan Ellis',
    isPublished: true,
    lessonsCount: 5,
    durationMinutes: 45,
    iconName: 'Laptop',
  },
  {
    id: 'course-reading-storybook-1',
    title: 'Interactive Storybook: The Clever Fox',
    description: 'Read the charming illustrated story with side-by-side sign video, tap-to-sign vocabulary, and sign-to-text games.',
    gradeLevel: 'Grade K-3',
    category: 'Reading & Literacy',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&auto=format&fit=crop&q=80',
    teacherId: 'user-teacher-1',
    teacherName: 'Mr. Jordan Ellis',
    isPublished: true,
    lessonsCount: 2,
    durationMinutes: 30,
    iconName: 'BookOpen',
  },
  {
    id: 'course-everyday-signs-1',
    title: 'Everyday Signs & Fingerspelling Mastery',
    description: 'Master daily ASL vocabulary including school items, emotions, colors, and the full fingerspelling alphabet.',
    gradeLevel: 'Grade K-5',
    category: 'Everyday Signs',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&auto=format&fit=crop&q=80',
    teacherId: 'user-teacher-1',
    teacherName: 'Mr. Jordan Ellis',
    isPublished: true,
    lessonsCount: 4,
    durationMinutes: 60,
    iconName: 'HandMetal',
  },
  {
    id: 'course-stem-planets-1',
    title: 'STEM: Space, Planets & Solar System Signs',
    description: 'Visual science exploration: Sun, Moon, Earth, Mars and orbit signs explained visually with interactive planet matching.',
    gradeLevel: 'Grade 3-6',
    category: 'STEM',
    thumbnailUrl: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=600&auto=format&fit=crop&q=80',
    teacherId: 'user-teacher-1',
    teacherName: 'Mr. Jordan Ellis',
    isPublished: true,
    lessonsCount: 3,
    durationMinutes: 40,
    iconName: 'Rocket',
  },
];

export const MOCK_WORKSHEETS: Record<string, Worksheet> = {
  'ws-hardware-match': {
    id: 'ws-hardware-match',
    lessonId: 'lesson-hardware-1',
    title: 'Hardware: Picture-to-Sign Match',
    activityType: 'picture_to_sign',
    instructions: 'Tap a computer picture on the left, then tap the matching sign description on the right!',
    totalPoints: 40,
    pairs: [
      {
        id: 'p-1',
        leftLabel: 'Webcam',
        leftMediaUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&auto=format&fit=crop&q=80',
        rightLabel: 'Sign: Camera lens focused on hands',
        rightMediaUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=300&auto=format&fit=crop&q=80',
        signHint: 'Hand shapes like a camera eye pointing at your signing space',
      },
      {
        id: 'p-2',
        leftLabel: 'Keyboard',
        leftMediaUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&auto=format&fit=crop&q=80',
        rightLabel: 'Sign: Wiggling fingers tapping flat desk',
        rightMediaUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&auto=format&fit=crop&q=80',
        signHint: 'Fingers fluttering across keys on table',
      },
      {
        id: 'p-3',
        leftLabel: 'Mouse',
        leftMediaUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=300&auto=format&fit=crop&q=80',
        rightLabel: 'Sign: Curved index finger clicking twice',
        rightMediaUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=300&auto=format&fit=crop&q=80',
        signHint: 'Bent finger mimics clicking left click button',
      },
      {
        id: 'p-4',
        leftLabel: 'Monitor',
        leftMediaUrl: 'https://images.unsplash.com/photo-1547394765-185e131e4184?w=300&auto=format&fit=crop&q=80',
        rightLabel: 'Sign: Tracing glowing screen rectangle',
        rightMediaUrl: 'https://images.unsplash.com/photo-1547394765-185e131e4184?w=300&auto=format&fit=crop&q=80',
        signHint: 'Both L-handshapes frame a wide screen display',
      },
    ],
  },
  'ws-sign-to-text-animals': {
    id: 'ws-sign-to-text-animals',
    lessonId: 'lesson-storybook-1',
    title: 'Sign-to-Text Vocabulary Match',
    activityType: 'sign_to_text',
    instructions: 'Look at the sign video description and select the correct written English word!',
    totalPoints: 30,
    multipleChoice: [
      {
        id: 'q-1',
        promptSignUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=300&auto=format&fit=crop&q=80',
        questionText: 'Sign: Whiskers stroked outward from cheeks with index and thumb',
        options: [
          { id: 'opt-1a', label: 'Cat', isCorrect: true },
          { id: 'opt-1b', label: 'Dog', isCorrect: false },
          { id: 'opt-1c', label: 'Bear', isCorrect: false },
        ],
      },
      {
        id: 'q-2',
        promptSignUrl: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=300&auto=format&fit=crop&q=80',
        questionText: 'Sign: Patting thigh then snapping fingers with palm up',
        options: [
          { id: 'opt-2a', label: 'Bird', isCorrect: false },
          { id: 'opt-2b', label: 'Dog', isCorrect: true },
          { id: 'opt-2c', label: 'Fish', isCorrect: false },
        ],
      },
      {
        id: 'q-3',
        promptSignUrl: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?w=300&auto=format&fit=crop&q=80',
        questionText: 'Sign: Arms crossed over chest scratching shoulders',
        options: [
          { id: 'opt-3a', label: 'Bear', isCorrect: true },
          { id: 'opt-3b', label: 'Fox', isCorrect: false },
          { id: 'opt-3c', label: 'Rabbit', isCorrect: false },
        ],
      },
    ],
  },
  'ws-fingerspell-builder': {
    id: 'ws-fingerspell-builder',
    lessonId: 'lesson-hardware-1',
    title: 'Fingerspell Word Builder: W-E-B',
    activityType: 'fingerspell_builder',
    instructions: 'Tap the fingerspelling tiles in the right order to spell the word WEB!',
    totalPoints: 20,
    targetFingerspellWord: 'WEB',
    availableLetterTiles: ['B', 'W', 'T', 'E', 'M', 'S'],
  },
};

export const MOCK_LESSONS: Record<string, Lesson> = {
  'lesson-hardware-1': {
    id: 'lesson-hardware-1',
    courseId: 'course-digital-literacy-1',
    title: 'Lesson 1: Computer Hardware Signs & Functions',
    lessonType: 'standard_lesson',
    description: 'Learn how to sign Monitor, Keyboard, Mouse, and Webcam, and discover how Deaf students use them to communicate.',
    signVideoUrl: 'https://www.youtube.com/watch?v=0FcwzMq4iWg',
    durationSeconds: 180,
    orderIndex: 1,
    vocabularyItems: [
      {
        id: 'vocab-webcam',
        textWord: 'Webcam',
        pictureUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&auto=format&fit=crop&q=80',
        signVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        fingerspellText: 'W E B C A M',
        category: 'Hardware',
        descriptionTips: 'Form C-shape camera lens pointing outward towards your signing space.',
      },
      {
        id: 'vocab-keyboard',
        textWord: 'Keyboard',
        pictureUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&auto=format&fit=crop&q=80',
        signVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        fingerspellText: 'K E Y B O A R D',
        category: 'Hardware',
        descriptionTips: 'Fingers wiggling downward across a horizontal plane.',
      },
      {
        id: 'vocab-monitor',
        textWord: 'Monitor',
        pictureUrl: 'https://images.unsplash.com/photo-1547394765-185e131e4184?w=300&auto=format&fit=crop&q=80',
        signVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        fingerspellText: 'M O N I T O R',
        category: 'Hardware',
        descriptionTips: 'Index fingers and thumbs trace a wide glowing display rectangle.',
      },
      {
        id: 'vocab-mouse',
        textWord: 'Mouse',
        pictureUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=300&auto=format&fit=crop&q=80',
        signVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        fingerspellText: 'M O U S E',
        category: 'Hardware',
        descriptionTips: 'Curved index finger clicks downward twice like clicking.',
      },
    ],
  },
  'lesson-keyboard-1': {
    id: 'lesson-keyboard-1',
    courseId: 'course-digital-literacy-1',
    title: 'Lesson 2: Fingerspelling QWERTY Typing & Handshapes',
    lessonType: 'standard_lesson',
    description: 'Connect AnySign handshapes with physical QWERTY keys. Master home-row typing A-S-D-F and J-K-L-;',
    signVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    durationSeconds: 200,
    orderIndex: 2,
    vocabularyItems: [
      {
        id: 'vocab-spacebar',
        textWord: 'Spacebar',
        pictureUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300',
        signVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        fingerspellText: 'S P A C E',
        category: 'Keyboard',
        descriptionTips: 'Both thumbs tap downward smoothly along the bottom horizontal bar.',
      },
      {
        id: 'vocab-enter',
        textWord: 'Enter Key',
        pictureUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300',
        signVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        fingerspellText: 'E N T E R',
        category: 'Keyboard',
        descriptionTips: 'Index finger swoops left and downward with a firm press.',
      },
    ],
  },
  'lesson-web-1': {
    id: 'lesson-web-1',
    courseId: 'course-digital-literacy-1',
    title: 'Lesson 3: Web Browser Navigation & Safe Online Signs',
    lessonType: 'standard_lesson',
    description: 'Learn signs for Website, Search, URL Link, and Internet Safety with visual verification cues.',
    signVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    durationSeconds: 210,
    orderIndex: 3,
    vocabularyItems: [
      {
        id: 'vocab-internet',
        textWord: 'Internet',
        pictureUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=300',
        signVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        fingerspellText: 'N E T',
        category: 'Web',
        descriptionTips: 'Middle fingertips brush against each other rotating in a fluid wave.',
      },
    ],
  },
  'lesson-everyday-1': {
    id: 'lesson-everyday-1',
    courseId: 'course-digital-literacy-1',
    title: 'Lesson 4: Everyday Signs for School & Home',
    lessonType: 'standard_lesson',
    description: 'Essential greetings, questions, classroom items, and expressions to build daily sign communication at home.',
    signVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    durationSeconds: 190,
    orderIndex: 4,
    vocabularyItems: [
      {
        id: 'vocab-hello',
        textWord: 'Hello',
        pictureUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=300',
        signVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        fingerspellText: 'H E L L O',
        category: 'Everyday',
        descriptionTips: 'Open flat hand salutes outward from the temple with a warm nod.',
      },
    ],
  },
  'lesson-storybook-1': {
    id: 'lesson-storybook-1',
    courseId: 'course-digital-literacy-1',
    title: 'Lesson 5: Storybook: The Clever Fox & The Forest Friends',
    lessonType: 'interactive_storybook',
    description: 'An interactive dual-pane visual storybook. Tap any word to see the sign demonstration!',
    signVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    durationSeconds: 240,
    orderIndex: 1,
    storyPages: [
      {
        pageNumber: 1,
        illustrationUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&auto=format&fit=crop&q=80',
        textContent: 'Deep in the green forest, a clever Fox loved to explore every morning. He greeted his friend the wise Bear by the sparkling river.',
        signVideoTimestamp: 0,
        highlightWords: [
          { word: 'Fox', signUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=300' },
          { word: 'Bear', signUrl: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?w=300' },
          { word: 'River', signUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=300' },
        ],
      },
      {
        pageNumber: 2,
        illustrationUrl: 'https://images.unsplash.com/photo-1511497584788-87676104235f?w=800&auto=format&fit=crop&q=80',
        textContent: 'The wise Bear smiled and signed: "Good morning Fox! Today we are learning how computers help animals share stories across the world."',
        signVideoTimestamp: 15,
        highlightWords: [
          { word: 'Smiled', signUrl: 'https://images.unsplash.com/photo-1511497584788-87676104235f?w=300' },
          { word: 'Computers', signUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=300' },
        ],
      },
      {
        pageNumber: 3,
        illustrationUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
        textContent: 'Together, they turned on their laptop. On the glowing screen, other friends were signing hello through the clear webcam!',
        signVideoTimestamp: 30,
        highlightWords: [
          { word: 'Laptop', signUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=300' },
          { word: 'Webcam', signUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300' },
        ],
      },
    ],
  },
};
